; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28314.0 

	TITLE	e:\visual studio application\????????????\thatboyencryptfileencoder\thatboyencryptfileencoder.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BP@MGHGNFFK@?S?$KG?S?C?$LD?L?P?r?O?r?$LF?$LM?I?z?$LD?I?$LF?D?$LB?$LO?$LF?X?S?$KG?S?C?$LD?L?P?r@ ; `string'
PUBLIC	??_R2CThatboyEncryptFileEncoderApp@@8		; CThatboyEncryptFileEncoderApp::`RTTI Base Class Array'
PUBLIC	??_R2CWinApp@@8					; CWinApp::`RTTI Base Class Array'
PUBLIC	??_R2CWinThread@@8				; CWinThread::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CThatboyEncryptFileEncoderApp@@8	; CThatboyEncryptFileEncoderApp::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CWinApp@@8			; CWinApp::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCCmdTarget@@@8				; CCmdTarget `RTTI Type Descriptor'
PUBLIC	??_R2CCmdTarget@@8				; CCmdTarget::`RTTI Base Class Array'
PUBLIC	??_R3CCmdTarget@@8				; CCmdTarget::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R1A@?0A@EA@CCmdTarget@@8			; CCmdTarget::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CWinThread@@8			; CWinThread::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3CWinApp@@8					; CWinApp::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVCWinApp@@@8				; CWinApp `RTTI Type Descriptor'
PUBLIC	??_R3CWinThread@@8				; CWinThread::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVCWinThread@@@8				; CWinThread `RTTI Type Descriptor'
PUBLIC	??_R3CThatboyEncryptFileEncoderApp@@8		; CThatboyEncryptFileEncoderApp::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVCThatboyEncryptFileEncoderApp@@@8	; CThatboyEncryptFileEncoderApp `RTTI Type Descriptor'
PUBLIC	??_R4CThatboyEncryptFileEncoderApp@@6B@		; CThatboyEncryptFileEncoderApp::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCBrush@@@8				; CBrush `RTTI Type Descriptor'
PUBLIC	??_R1A@?0A@EA@CBrush@@8				; CBrush::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R2CBrush@@8					; CBrush::`RTTI Base Class Array'
PUBLIC	??_R3CBrush@@8					; CBrush::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R4CBrush@@6B@				; CBrush::`RTTI Complete Object Locator'
PUBLIC	??_7CBrush@@6B@					; CBrush::`vftable'
PUBLIC	??_R0?AVCGdiObject@@@8				; CGdiObject `RTTI Type Descriptor'
PUBLIC	??_R1A@?0A@EA@CGdiObject@@8			; CGdiObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCObject@@@8				; CObject `RTTI Type Descriptor'
PUBLIC	??_R2CObject@@8					; CObject::`RTTI Base Class Array'
PUBLIC	??_R3CObject@@8					; CObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R1A@?0A@EA@CObject@@8			; CObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R2CGdiObject@@8				; CGdiObject::`RTTI Base Class Array'
PUBLIC	??_R3CGdiObject@@8				; CGdiObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R4CGdiObject@@6B@				; CGdiObject::`RTTI Complete Object Locator'
PUBLIC	??_7CGdiObject@@6B@				; CGdiObject::`vftable'
PUBLIC	??_R0PAVCException@@@8				; CException * `RTTI Type Descriptor'
PUBLIC	??_C@_0BB@HBOOMJBF@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ?6?$CFTs@ ; `string'
PUBLIC	??_C@_0HD@FGOICIBN@C?3?2Program?5Files?5?$CIx86?$CJ?2Microsof@ ; `string'
PUBLIC	??_C@_0BP@OIEOKIDM@Exception?5thrown?5in?5destructor@ ; `string'
PUBLIC	??_C@_0N@OMEMOKLE@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ@ ; `string'
PUBLIC	??_7CThatboyEncryptFileEncoderApp@@6B@		; CThatboyEncryptFileEncoderApp::`vftable'
EXTRN	__imp_?LoadSysPolicies@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?LoadAppLangResourceDLL@CWinApp@@UAEPAUHINSTANCE__@@XZ:PROC
EXTRN	__imp_?RestartInstance@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?IsTaskbarInteractionEnabled@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?GetDataRecoveryHandler@CWinApp@@UAEPAVCDataRecoveryHandler@@XZ:PROC
EXTRN	__imp_?ApplicationRecoveryCallback@CWinApp@@UAEKPAX@Z:PROC
EXTRN	__imp_?RegisterWithRestartManager@CWinApp@@UAEJHABV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PROC
EXTRN	__imp_?RegisterWithRestartManager@CWinApp@@UAEJPB_WKP6GKPAX@Z1KK@Z:PROC
EXTRN	__imp_?WinHelpInternal@CWinApp@@UAEXKI@Z:PROC
EXTRN	__imp_?HtmlHelpA@CWinApp@@UAEXKI@Z:PROC
EXTRN	__imp_?WinHelpA@CWinApp@@UAEXKI@Z:PROC
EXTRN	__imp_?OnDDECommand@CWinApp@@UAEHPAD@Z:PROC
EXTRN	__imp_?DoWaitCursor@CWinApp@@UAEXH@Z:PROC
EXTRN	__imp_?DoMessageBox@CWinApp@@UAEHPBDII@Z:PROC
EXTRN	__imp_?SaveAllModified@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?InitApplication@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?AddToRecentFileList@CWinApp@@UAEXPBD@Z:PROC
EXTRN	__imp_?OpenDocumentFile@CWinApp@@UAEPAVCDocument@@PBD@Z:PROC
EXTRN	__imp_?OpenDocumentFile@CWinApp@@UAEPAVCDocument@@PBDH@Z:PROC
EXTRN	__imp_?Unregister@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?Register@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?InitLibId@CWinApp@@UAEXXZ:PROC
EXTRN	__imp_?WriteProfileBinary@CWinApp@@UAEHPBD0PAEI@Z:PROC
EXTRN	__imp_?GetProfileBinary@CWinApp@@UAEHPBD0PAPAEPAI@Z:PROC
EXTRN	__imp_?WriteProfileStringA@CWinApp@@UAEHPBD00@Z:PROC
EXTRN	__imp_?GetProfileStringA@CWinApp@@UAE?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PBD00@Z:PROC
EXTRN	__imp_?WriteProfileInt@CWinApp@@UAEHPBD0H@Z:PROC
EXTRN	__imp_?GetProfileIntA@CWinApp@@UAEIPBD0H@Z:PROC
EXTRN	__imp_?Delete@CWinThread@@UAEXXZ:PROC
EXTRN	__imp_?GetMainWnd@CWinThread@@UAEPAVCWnd@@XZ:PROC
EXTRN	__imp_?ProcessMessageFilter@CWinThread@@UAEHHPAUtagMSG@@@Z:PROC
EXTRN	__imp_?ProcessWndProcException@CWinApp@@UAEJPAVCException@@PBUtagMSG@@@Z:PROC
EXTRN	__imp_?ExitInstance@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?IsIdleMessage@CWinThread@@UAEHPAUtagMSG@@@Z:PROC
EXTRN	__imp_?OnIdle@CWinApp@@UAEHJ@Z:PROC
EXTRN	__imp_?PumpMessage@CWinThread@@UAEHXZ:PROC
EXTRN	__imp_?PreTranslateMessage@CWinThread@@UAEHPAUtagMSG@@@Z:PROC
EXTRN	__imp_?Run@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z:PROC
EXTRN	__imp_?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z:PROC
EXTRN	__imp_?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z:PROC
EXTRN	__imp_?OnCreateAggregates@CCmdTarget@@UAEHXZ:PROC
EXTRN	__imp_?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ:PROC
EXTRN	__imp_?GetInterfaceMap@CCmdTarget@@MBEPBUAFX_INTERFACEMAP@@XZ:PROC
EXTRN	__imp_?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ:PROC
EXTRN	__imp_?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ:PROC
EXTRN	__imp_?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ:PROC
EXTRN	__imp_?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z:PROC
EXTRN	__imp_?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ:PROC
EXTRN	__imp_?GetTypeInfoCount@CCmdTarget@@UAEIXZ:PROC
EXTRN	__imp_?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z:PROC
EXTRN	__imp_?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z:PROC
EXTRN	__imp_?OnFinalRelease@CCmdTarget@@UAEXXZ:PROC
EXTRN	__imp_?OnCmdMsg@CCmdTarget@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z:PROC
EXTRN	__imp_?GetRuntimeClass@CWinApp@@UBEPAUCRuntimeClass@@XZ:PROC
EXTRN	__imp_??1CDialogImpl@@MAE@XZ:PROC
EXTRN	__imp_?GetRuntimeClass@CBrush@@UBEPAUCRuntimeClass@@XZ:PROC
EXTRN	__imp_?GetRuntimeClass@CGdiObject@@UBEPAUCRuntimeClass@@XZ:PROC
EXTRN	__imp_?DeleteObject@CGdiObject@@QAEHXZ:PROC
EXTRN	__imp_??0?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAE@XZ:PROC
EXTRN	__imp_??1?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAE@XZ:PROC
EXTRN	__imp_?Format@?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAAXPBDZZ:PROC
EXTRN	__imp_?AfxMessageBox@@YGHPBDII@Z:PROC
EXTRN	__imp_??B?$CSimpleStringT@D$00@ATL@@QBEPBDXZ:PROC
EXTRN	__imp_??1CDialog@@UAE@XZ:PROC
EXTRN	__imp_??1CToolTipCtrl@@UAE@XZ:PROC
EXTRN	__imp_?DoModal@CDialog@@UAEHXZ:PROC
EXTRN	__imp_?SetRegistryKey@CWinApp@@IAEXPBD@Z:PROC
EXTRN	__imp_?GetThisClass@CMFCVisualManagerWindows@@SGPAUCRuntimeClass@@XZ:PROC
EXTRN	__imp_?SetDefaultManager@CMFCVisualManager@@SGXPAUCRuntimeClass@@@Z:PROC
EXTRN	__imp_??0CShellManager@@QAE@XZ:PROC
EXTRN	__imp_?InitInstance@CWinApp@@UAEHXZ:PROC
EXTRN	__imp_??3@YAXPAX@Z:PROC
EXTRN	__imp_??1CWinApp@@UAE@XZ:PROC
EXTRN	__imp_??0CWinApp@@QAE@PBD@Z:PROC
EXTRN	__imp_?GetThisMessageMap@CWinApp@@KGPBUAFX_MSGMAP@@XZ:PROC
EXTRN	__imp_?OnHelp@CWinApp@@IAEXXZ:PROC
EXTRN	?GetProfileStringA@CWinApp@@UAE?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PBD00@Z:PROC ; CWinApp::GetProfileStringA
EXTRN	?WriteProfileInt@CWinApp@@UAEHPBD0H@Z:PROC	; CWinApp::WriteProfileInt
EXTRN	?Delete@CWinThread@@UAEXXZ:PROC			; CWinThread::Delete
EXTRN	?PreTranslateMessage@CWinThread@@UAEHPAUtagMSG@@@Z:PROC ; CWinThread::PreTranslateMessage
EXTRN	?GetProfileIntA@CWinApp@@UAEIPBD0H@Z:PROC	; CWinApp::GetProfileIntA
EXTRN	?GetMainWnd@CWinThread@@UAEPAVCWnd@@XZ:PROC	; CWinThread::GetMainWnd
EXTRN	?ProcessWndProcException@CWinApp@@UAEJPAVCException@@PBUtagMSG@@@Z:PROC ; CWinApp::ProcessWndProcException
EXTRN	?IsIdleMessage@CWinThread@@UAEHPAUtagMSG@@@Z:PROC ; CWinThread::IsIdleMessage
EXTRN	?Run@CWinApp@@UAEHXZ:PROC			; CWinApp::Run
EXTRN	?OnIdle@CWinApp@@UAEHJ@Z:PROC			; CWinApp::OnIdle
EXTRN	?PumpMessage@CWinThread@@UAEHXZ:PROC		; CWinThread::PumpMessage
EXTRN	?ProcessMessageFilter@CWinThread@@UAEHHPAUtagMSG@@@Z:PROC ; CWinThread::ProcessMessageFilter
EXTRN	?OnCreateAggregates@CCmdTarget@@UAEHXZ:PROC	; CCmdTarget::OnCreateAggregates
EXTRN	?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ:PROC ; CCmdTarget::GetEventSinkMap
EXTRN	?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z:PROC ; CCmdTarget::GetConnectionHook
EXTRN	?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z:PROC ; CCmdTarget::GetExtraConnectionPoints
EXTRN	?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z:PROC ; CCmdTarget::GetInterfaceHook
EXTRN	?GetInterfaceMap@CCmdTarget@@MBEPBUAFX_INTERFACEMAP@@XZ:PROC ; CCmdTarget::GetInterfaceMap
EXTRN	?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ:PROC ; CCmdTarget::GetConnectionMap
EXTRN	?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ:PROC ; CCmdTarget::GetDispatchMap
EXTRN	?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ:PROC ; CCmdTarget::GetCommandMap
EXTRN	?ExitInstance@CWinApp@@UAEHXZ:PROC		; CWinApp::ExitInstance
EXTRN	?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ:PROC ; CCmdTarget::GetTypeLibCache
EXTRN	?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z:PROC	; CCmdTarget::IsInvokeAllowed
EXTRN	?OnFinalRelease@CCmdTarget@@UAEXXZ:PROC		; CCmdTarget::OnFinalRelease
EXTRN	?GetTypeInfoCount@CCmdTarget@@UAEIXZ:PROC	; CCmdTarget::GetTypeInfoCount
EXTRN	?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z:PROC ; CCmdTarget::GetDispatchIID
EXTRN	?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z:PROC ; CCmdTarget::GetTypeLib
EXTRN	?OnCmdMsg@CCmdTarget@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z:PROC ; CCmdTarget::OnCmdMsg
EXTRN	?GetRuntimeClass@CWinApp@@UBEPAUCRuntimeClass@@XZ:PROC ; CWinApp::GetRuntimeClass
EXTRN	?GetRuntimeClass@CBrush@@UBEPAUCRuntimeClass@@XZ:PROC ; CBrush::GetRuntimeClass
EXTRN	?ApplicationRecoveryCallback@CWinApp@@UAEKPAX@Z:PROC ; CWinApp::ApplicationRecoveryCallback
EXTRN	?RegisterWithRestartManager@CWinApp@@UAEJHABV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PROC ; CWinApp::RegisterWithRestartManager
EXTRN	?HtmlHelpA@CWinApp@@UAEXKI@Z:PROC		; CWinApp::HtmlHelpA
EXTRN	?WinHelpA@CWinApp@@UAEXKI@Z:PROC		; CWinApp::WinHelpA
EXTRN	?OnDDECommand@CWinApp@@UAEHPAD@Z:PROC		; CWinApp::OnDDECommand
EXTRN	?DoWaitCursor@CWinApp@@UAEXH@Z:PROC		; CWinApp::DoWaitCursor
EXTRN	?InitApplication@CWinApp@@UAEHXZ:PROC		; CWinApp::InitApplication
EXTRN	?AddToRecentFileList@CWinApp@@UAEXPBD@Z:PROC	; CWinApp::AddToRecentFileList
EXTRN	?RegisterWithRestartManager@CWinApp@@UAEJPB_WKP6GKPAX@Z1KK@Z:PROC ; CWinApp::RegisterWithRestartManager
EXTRN	?WinHelpInternal@CWinApp@@UAEXKI@Z:PROC		; CWinApp::WinHelpInternal
EXTRN	?DoMessageBox@CWinApp@@UAEHPBDII@Z:PROC		; CWinApp::DoMessageBox
EXTRN	?SaveAllModified@CWinApp@@UAEHXZ:PROC		; CWinApp::SaveAllModified
EXTRN	?OpenDocumentFile@CWinApp@@UAEPAVCDocument@@PBD@Z:PROC ; CWinApp::OpenDocumentFile
EXTRN	?Register@CWinApp@@UAEHXZ:PROC			; CWinApp::Register
EXTRN	?InitLibId@CWinApp@@UAEXXZ:PROC			; CWinApp::InitLibId
EXTRN	?WriteProfileBinary@CWinApp@@UAEHPBD0PAEI@Z:PROC ; CWinApp::WriteProfileBinary
EXTRN	?GetProfileBinary@CWinApp@@UAEHPBD0PAPAEPAI@Z:PROC ; CWinApp::GetProfileBinary
EXTRN	?WriteProfileStringA@CWinApp@@UAEHPBD00@Z:PROC	; CWinApp::WriteProfileStringA
EXTRN	?OpenDocumentFile@CWinApp@@UAEPAVCDocument@@PBDH@Z:PROC ; CWinApp::OpenDocumentFile
EXTRN	?Unregister@CWinApp@@UAEHXZ:PROC		; CWinApp::Unregister
EXTRN	?LoadSysPolicies@CWinApp@@UAEHXZ:PROC		; CWinApp::LoadSysPolicies
EXTRN	?LoadAppLangResourceDLL@CWinApp@@UAEPAUHINSTANCE__@@XZ:PROC ; CWinApp::LoadAppLangResourceDLL
EXTRN	?RestartInstance@CWinApp@@UAEHXZ:PROC		; CWinApp::RestartInstance
EXTRN	?IsTaskbarInteractionEnabled@CWinApp@@UAEHXZ:PROC ; CWinApp::IsTaskbarInteractionEnabled
EXTRN	?GetDataRecoveryHandler@CWinApp@@UAEPAVCDataRecoveryHandler@@XZ:PROC ; CWinApp::GetDataRecoveryHandler
EXTRN	?GetThisMessageMap@CWinApp@@KGPBUAFX_MSGMAP@@XZ:PROC ; CWinApp::GetThisMessageMap
EXTRN	?OnHelp@CWinApp@@IAEXXZ:PROC			; CWinApp::OnHelp
EXTRN	?DoModal@CDialog@@UAEHXZ:PROC			; CDialog::DoModal
EXTRN	?GetRuntimeClass@CGdiObject@@UBEPAUCRuntimeClass@@XZ:PROC ; CGdiObject::GetRuntimeClass
;	COMDAT ?_messageEntries@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B
CONST	SEGMENT
?_messageEntries@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B DD 0111H ; `CThatboyEncryptFileEncoderApp::GetThisMessageMap'::`2'::_messageEntries
	DD	00H
	DD	0e146H
	DD	0e146H
	DD	03aH
	DD	FLAT:?OnHelp@CWinApp@@IAEXXZ
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
;	COMDAT ?messageMap@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4U3@B
CONST	SEGMENT
?messageMap@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4U3@B DD FLAT:?GetThisMessageMap@CWinApp@@KGPBUAFX_MSGMAP@@XZ ; `CThatboyEncryptFileEncoderApp::GetThisMessageMap'::`2'::messageMap
	DD	FLAT:?_messageEntries@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B
CONST	ENDS
;	COMDAT ??_7CThatboyEncryptFileEncoderApp@@6B@
CONST	SEGMENT
??_7CThatboyEncryptFileEncoderApp@@6B@ DD FLAT:??_R4CThatboyEncryptFileEncoderApp@@6B@ ; CThatboyEncryptFileEncoderApp::`vftable'
	DD	FLAT:?GetRuntimeClass@CWinApp@@UBEPAUCRuntimeClass@@XZ
	DD	FLAT:??_ECThatboyEncryptFileEncoderApp@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CObject@@UBEXXZ
	DD	FLAT:?Dump@CObject@@UBEXAAVCDumpContext@@@Z
	DD	FLAT:?OnCmdMsg@CCmdTarget@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z
	DD	FLAT:?OnFinalRelease@CCmdTarget@@UAEXXZ
	DD	FLAT:?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z
	DD	FLAT:?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z
	DD	FLAT:?GetTypeInfoCount@CCmdTarget@@UAEIXZ
	DD	FLAT:?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ
	DD	FLAT:?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z
	DD	FLAT:?GetMessageMap@CThatboyEncryptFileEncoderApp@@MBEPBUAFX_MSGMAP@@XZ
	DD	FLAT:?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ
	DD	FLAT:?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ
	DD	FLAT:?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ
	DD	FLAT:?GetInterfaceMap@CCmdTarget@@MBEPBUAFX_INTERFACEMAP@@XZ
	DD	FLAT:?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ
	DD	FLAT:?OnCreateAggregates@CCmdTarget@@UAEHXZ
	DD	FLAT:?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z
	DD	FLAT:?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z
	DD	FLAT:?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z
	DD	FLAT:?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ
	DD	FLAT:?Run@CWinApp@@UAEHXZ
	DD	FLAT:?PreTranslateMessage@CWinThread@@UAEHPAUtagMSG@@@Z
	DD	FLAT:?PumpMessage@CWinThread@@UAEHXZ
	DD	FLAT:?OnIdle@CWinApp@@UAEHJ@Z
	DD	FLAT:?IsIdleMessage@CWinThread@@UAEHPAUtagMSG@@@Z
	DD	FLAT:?ExitInstance@CWinApp@@UAEHXZ
	DD	FLAT:?ProcessWndProcException@CWinApp@@UAEJPAVCException@@PBUtagMSG@@@Z
	DD	FLAT:?ProcessMessageFilter@CWinThread@@UAEHHPAUtagMSG@@@Z
	DD	FLAT:?GetMainWnd@CWinThread@@UAEPAVCWnd@@XZ
	DD	FLAT:?Delete@CWinThread@@UAEXXZ
	DD	FLAT:?GetProfileIntA@CWinApp@@UAEIPBD0H@Z
	DD	FLAT:?WriteProfileInt@CWinApp@@UAEHPBD0H@Z
	DD	FLAT:?GetProfileStringA@CWinApp@@UAE?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PBD00@Z
	DD	FLAT:?WriteProfileStringA@CWinApp@@UAEHPBD00@Z
	DD	FLAT:?GetProfileBinary@CWinApp@@UAEHPBD0PAPAEPAI@Z
	DD	FLAT:?WriteProfileBinary@CWinApp@@UAEHPBD0PAEI@Z
	DD	FLAT:?InitLibId@CWinApp@@UAEXXZ
	DD	FLAT:?Register@CWinApp@@UAEHXZ
	DD	FLAT:?Unregister@CWinApp@@UAEHXZ
	DD	FLAT:?OpenDocumentFile@CWinApp@@UAEPAVCDocument@@PBDH@Z
	DD	FLAT:?OpenDocumentFile@CWinApp@@UAEPAVCDocument@@PBD@Z
	DD	FLAT:?AddToRecentFileList@CWinApp@@UAEXPBD@Z
	DD	FLAT:?InitApplication@CWinApp@@UAEHXZ
	DD	FLAT:?SaveAllModified@CWinApp@@UAEHXZ
	DD	FLAT:?DoMessageBox@CWinApp@@UAEHPBDII@Z
	DD	FLAT:?DoWaitCursor@CWinApp@@UAEXH@Z
	DD	FLAT:?OnDDECommand@CWinApp@@UAEHPAD@Z
	DD	FLAT:?WinHelpA@CWinApp@@UAEXKI@Z
	DD	FLAT:?HtmlHelpA@CWinApp@@UAEXKI@Z
	DD	FLAT:?WinHelpInternal@CWinApp@@UAEXKI@Z
	DD	FLAT:?RegisterWithRestartManager@CWinApp@@UAEJPB_WKP6GKPAX@Z1KK@Z
	DD	FLAT:?RegisterWithRestartManager@CWinApp@@UAEJHABV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z
	DD	FLAT:?ApplicationRecoveryCallback@CWinApp@@UAEKPAX@Z
	DD	FLAT:?SupportsRestartManager@CWinApp@@UBEHXZ
	DD	FLAT:?SupportsApplicationRecovery@CWinApp@@UBEHXZ
	DD	FLAT:?SupportsAutosaveAtRestart@CWinApp@@UBEHXZ
	DD	FLAT:?SupportsAutosaveAtInterval@CWinApp@@UBEHXZ
	DD	FLAT:?ReopenPreviousFilesAtRestart@CWinApp@@UBEHXZ
	DD	FLAT:?RestoreAutosavedFilesAtRestart@CWinApp@@UBEHXZ
	DD	FLAT:?GetApplicationRestartFlags@CWinApp@@UAEKXZ
	DD	FLAT:?GetApplicationRecoveryParameter@CWinApp@@UAEPAXXZ
	DD	FLAT:?GetApplicationRecoveryPingInterval@CWinApp@@UAEKXZ
	DD	FLAT:?GetDataRecoveryHandler@CWinApp@@UAEPAVCDataRecoveryHandler@@XZ
	DD	FLAT:?IsTaskbarInteractionEnabled@CWinApp@@UAEHXZ
	DD	FLAT:?RestartInstance@CWinApp@@UAEHXZ
	DD	FLAT:?LoadAppLangResourceDLL@CWinApp@@UAEPAUHINSTANCE__@@XZ
	DD	FLAT:?LoadSysPolicies@CWinApp@@UAEHXZ
CONST	ENDS
;	COMDAT ??_C@_0N@OMEMOKLE@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ@
CONST	SEGMENT
??_C@_0N@OMEMOKLE@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ@ DB '%Ts (%Ts:%d)', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BP@OIEOKIDM@Exception?5thrown?5in?5destructor@
CONST	SEGMENT
??_C@_0BP@OIEOKIDM@Exception?5thrown?5in?5destructor@ DB 'Exception throw'
	DB	'n in destructor', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0HD@FGOICIBN@C?3?2Program?5Files?5?$CIx86?$CJ?2Microsof@
CONST	SEGMENT
??_C@_0HD@FGOICIBN@C?3?2Program?5Files?5?$CIx86?$CJ?2Microsof@ DB 'C:\Pro'
	DB	'gram Files (x86)\Microsoft Visual Studio\2019\Community\VC\To'
	DB	'ols\MSVC\14.24.28314\atlmfc\include\afxwin1.inl', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@HBOOMJBF@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ?6?$CFTs@
CONST	SEGMENT
??_C@_0BB@HBOOMJBF@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ?6?$CFTs@ DB '%Ts (%Ts:%d'
	DB	')', 0aH, '%Ts', 00H				; `string'
CONST	ENDS
;	COMDAT ??_R0PAVCException@@@8
data$r	SEGMENT
??_R0PAVCException@@@8 DD FLAT:??_7type_info@@6B@	; CException * `RTTI Type Descriptor'
	DD	00H
	DB	'.PAVCException@@', 00H
data$r	ENDS
;	COMDAT ??_7CGdiObject@@6B@
CONST	SEGMENT
??_7CGdiObject@@6B@ DD FLAT:??_R4CGdiObject@@6B@	; CGdiObject::`vftable'
	DD	FLAT:?GetRuntimeClass@CGdiObject@@UBEPAUCRuntimeClass@@XZ
	DD	FLAT:??_ECGdiObject@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CObject@@UBEXXZ
	DD	FLAT:?Dump@CObject@@UBEXAAVCDumpContext@@@Z
CONST	ENDS
;	COMDAT ??_R4CGdiObject@@6B@
rdata$r	SEGMENT
??_R4CGdiObject@@6B@ DD 00H				; CGdiObject::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCGdiObject@@@8
	DD	FLAT:??_R3CGdiObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CGdiObject@@8
rdata$r	SEGMENT
??_R3CGdiObject@@8 DD 00H				; CGdiObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CGdiObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CGdiObject@@8
rdata$r	SEGMENT
??_R2CGdiObject@@8 DD FLAT:??_R1A@?0A@EA@CGdiObject@@8	; CGdiObject::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CObject@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CObject@@8 DD FLAT:??_R0?AVCObject@@@8	; CObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CObject@@8
rdata$r	SEGMENT
??_R3CObject@@8 DD 00H					; CObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CObject@@8
rdata$r	SEGMENT
??_R2CObject@@8 DD FLAT:??_R1A@?0A@EA@CObject@@8	; CObject::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R0?AVCObject@@@8
data$r	SEGMENT
??_R0?AVCObject@@@8 DD FLAT:??_7type_info@@6B@		; CObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCObject@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CGdiObject@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CGdiObject@@8 DD FLAT:??_R0?AVCGdiObject@@@8 ; CGdiObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CGdiObject@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCGdiObject@@@8
data$r	SEGMENT
??_R0?AVCGdiObject@@@8 DD FLAT:??_7type_info@@6B@	; CGdiObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCGdiObject@@', 00H
data$r	ENDS
;	COMDAT ??_7CBrush@@6B@
CONST	SEGMENT
??_7CBrush@@6B@ DD FLAT:??_R4CBrush@@6B@		; CBrush::`vftable'
	DD	FLAT:?GetRuntimeClass@CBrush@@UBEPAUCRuntimeClass@@XZ
	DD	FLAT:??_ECBrush@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CObject@@UBEXXZ
	DD	FLAT:?Dump@CObject@@UBEXAAVCDumpContext@@@Z
CONST	ENDS
;	COMDAT ??_R4CBrush@@6B@
rdata$r	SEGMENT
??_R4CBrush@@6B@ DD 00H					; CBrush::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCBrush@@@8
	DD	FLAT:??_R3CBrush@@8
rdata$r	ENDS
;	COMDAT ??_R3CBrush@@8
rdata$r	SEGMENT
??_R3CBrush@@8 DD 00H					; CBrush::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2CBrush@@8
rdata$r	ENDS
;	COMDAT ??_R2CBrush@@8
rdata$r	SEGMENT
??_R2CBrush@@8 DD FLAT:??_R1A@?0A@EA@CBrush@@8		; CBrush::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CGdiObject@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CBrush@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CBrush@@8 DD FLAT:??_R0?AVCBrush@@@8	; CBrush::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CBrush@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCBrush@@@8
data$r	SEGMENT
??_R0?AVCBrush@@@8 DD FLAT:??_7type_info@@6B@		; CBrush `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCBrush@@', 00H
data$r	ENDS
;	COMDAT ??_R4CThatboyEncryptFileEncoderApp@@6B@
rdata$r	SEGMENT
??_R4CThatboyEncryptFileEncoderApp@@6B@ DD 00H		; CThatboyEncryptFileEncoderApp::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCThatboyEncryptFileEncoderApp@@@8
	DD	FLAT:??_R3CThatboyEncryptFileEncoderApp@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCThatboyEncryptFileEncoderApp@@@8
data$r	SEGMENT
??_R0?AVCThatboyEncryptFileEncoderApp@@@8 DD FLAT:??_7type_info@@6B@ ; CThatboyEncryptFileEncoderApp `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCThatboyEncryptFileEncoderApp@@', 00H
data$r	ENDS
;	COMDAT ??_R3CThatboyEncryptFileEncoderApp@@8
rdata$r	SEGMENT
??_R3CThatboyEncryptFileEncoderApp@@8 DD 00H		; CThatboyEncryptFileEncoderApp::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	05H
	DD	FLAT:??_R2CThatboyEncryptFileEncoderApp@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCWinThread@@@8
data$r	SEGMENT
??_R0?AVCWinThread@@@8 DD FLAT:??_7type_info@@6B@	; CWinThread `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCWinThread@@', 00H
data$r	ENDS
;	COMDAT ??_R3CWinThread@@8
rdata$r	SEGMENT
??_R3CWinThread@@8 DD 00H				; CWinThread::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2CWinThread@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCWinApp@@@8
data$r	SEGMENT
??_R0?AVCWinApp@@@8 DD FLAT:??_7type_info@@6B@		; CWinApp `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCWinApp@@', 00H
data$r	ENDS
;	COMDAT ??_R3CWinApp@@8
rdata$r	SEGMENT
??_R3CWinApp@@8 DD 00H					; CWinApp::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	FLAT:??_R2CWinApp@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CWinThread@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CWinThread@@8 DD FLAT:??_R0?AVCWinThread@@@8 ; CWinThread::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CWinThread@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CCmdTarget@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CCmdTarget@@8 DD FLAT:??_R0?AVCCmdTarget@@@8 ; CCmdTarget::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CCmdTarget@@8
rdata$r	ENDS
;	COMDAT ??_R3CCmdTarget@@8
rdata$r	SEGMENT
??_R3CCmdTarget@@8 DD 00H				; CCmdTarget::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CCmdTarget@@8
rdata$r	ENDS
;	COMDAT ??_R2CCmdTarget@@8
rdata$r	SEGMENT
??_R2CCmdTarget@@8 DD FLAT:??_R1A@?0A@EA@CCmdTarget@@8	; CCmdTarget::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCCmdTarget@@@8
data$r	SEGMENT
??_R0?AVCCmdTarget@@@8 DD FLAT:??_7type_info@@6B@	; CCmdTarget `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCCmdTarget@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CWinApp@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CWinApp@@8 DD FLAT:??_R0?AVCWinApp@@@8	; CWinApp::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CWinApp@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CThatboyEncryptFileEncoderApp@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CThatboyEncryptFileEncoderApp@@8 DD FLAT:??_R0?AVCThatboyEncryptFileEncoderApp@@@8 ; CThatboyEncryptFileEncoderApp::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	04H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CThatboyEncryptFileEncoderApp@@8
rdata$r	ENDS
;	COMDAT ??_R2CWinThread@@8
rdata$r	SEGMENT
??_R2CWinThread@@8 DD FLAT:??_R1A@?0A@EA@CWinThread@@8	; CWinThread::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CWinApp@@8
rdata$r	SEGMENT
??_R2CWinApp@@8 DD FLAT:??_R1A@?0A@EA@CWinApp@@8	; CWinApp::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CWinThread@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CThatboyEncryptFileEncoderApp@@8
rdata$r	SEGMENT
??_R2CThatboyEncryptFileEncoderApp@@8 DD FLAT:??_R1A@?0A@EA@CThatboyEncryptFileEncoderApp@@8 ; CThatboyEncryptFileEncoderApp::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CWinApp@@8
	DD	FLAT:??_R1A@?0A@EA@CWinThread@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_C@_0BP@MGHGNFFK@?S?$KG?S?C?$LD?L?P?r?O?r?$LF?$LM?I?z?$LD?I?$LF?D?$LB?$LO?$LF?X?S?$KG?S?C?$LD?L?P?r@
CONST	SEGMENT
??_C@_0BP@MGHGNFFK@?S?$KG?S?C?$LD?L?P?r?O?r?$LF?$LM?I?z?$LD?I?$LF?D?$LB?$LO?$LF?X?S?$KG?S?C?$LD?L?P?r@ DB 0d3H
	DB	0a6H, 0d3H, 0c3H, 0b3H, 0ccH, 0d0H, 0f2H, 0cfH, 0f2H, 0b5H, 0bcH
	DB	0c9H, 0faH, 0b3H, 0c9H, 0b5H, 0c4H, 0b1H, 0beH, 0b5H, 0d8H, 0d3H
	DB	0a6H, 0d3H, 0c3H, 0b3H, 0ccH, 0d0H, 0f2H, 00H ; `string'
PUBLIC	??3CObject@@SGXPAX@Z				; CObject::operator delete
PUBLIC	??2CObject@@SGPAXI@Z				; CObject::operator new
PUBLIC	??1CBrush@@UAE@XZ				; CBrush::~CBrush
PUBLIC	??1CGdiObject@@UAE@XZ				; CGdiObject::~CGdiObject
PUBLIC	??1CObject@@UAE@XZ				; CObject::~CObject
PUBLIC	?Dump@CObject@@UBEXAAVCDumpContext@@@Z		; CObject::Dump
PUBLIC	?AssertValid@CObject@@UBEXXZ			; CObject::AssertValid
PUBLIC	?Serialize@CObject@@UAEXAAVCArchive@@@Z		; CObject::Serialize
PUBLIC	??_GCGdiObject@@UAEPAXI@Z			; CGdiObject::`scalar deleting destructor'
PUBLIC	??_GCBrush@@UAEPAXI@Z				; CBrush::`scalar deleting destructor'
PUBLIC	?SupportsRestartManager@CWinApp@@UBEHXZ		; CWinApp::SupportsRestartManager
PUBLIC	?SupportsApplicationRecovery@CWinApp@@UBEHXZ	; CWinApp::SupportsApplicationRecovery
PUBLIC	?SupportsAutosaveAtRestart@CWinApp@@UBEHXZ	; CWinApp::SupportsAutosaveAtRestart
PUBLIC	?SupportsAutosaveAtInterval@CWinApp@@UBEHXZ	; CWinApp::SupportsAutosaveAtInterval
PUBLIC	?ReopenPreviousFilesAtRestart@CWinApp@@UBEHXZ	; CWinApp::ReopenPreviousFilesAtRestart
PUBLIC	?RestoreAutosavedFilesAtRestart@CWinApp@@UBEHXZ	; CWinApp::RestoreAutosavedFilesAtRestart
PUBLIC	?GetApplicationRestartFlags@CWinApp@@UAEKXZ	; CWinApp::GetApplicationRestartFlags
PUBLIC	?GetApplicationRecoveryParameter@CWinApp@@UAEPAXXZ ; CWinApp::GetApplicationRecoveryParameter
PUBLIC	?GetApplicationRecoveryPingInterval@CWinApp@@UAEKXZ ; CWinApp::GetApplicationRecoveryPingInterval
PUBLIC	??1CDialogEx@@UAE@XZ				; CDialogEx::~CDialogEx
PUBLIC	??1CThatboyEncryptFileEncoderDlg@@UAE@XZ	; CThatboyEncryptFileEncoderDlg::~CThatboyEncryptFileEncoderDlg
PUBLIC	?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ ; CThatboyEncryptFileEncoderApp::InitInstance
PUBLIC	??1CThatboyEncryptFileEncoderApp@@UAE@XZ	; CThatboyEncryptFileEncoderApp::~CThatboyEncryptFileEncoderApp
PUBLIC	??_GCThatboyEncryptFileEncoderApp@@UAEPAXI@Z	; CThatboyEncryptFileEncoderApp::`scalar deleting destructor'
PUBLIC	??0CThatboyEncryptFileEncoderApp@@QAE@XZ	; CThatboyEncryptFileEncoderApp::CThatboyEncryptFileEncoderApp
PUBLIC	?GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ ; CThatboyEncryptFileEncoderApp::GetThisMessageMap
PUBLIC	?GetMessageMap@CThatboyEncryptFileEncoderApp@@MBEPBUAFX_MSGMAP@@XZ ; CThatboyEncryptFileEncoderApp::GetMessageMap
PUBLIC	?theApp@@3VCThatboyEncryptFileEncoderApp@@A	; theApp
EXTRN	?__global_delete@@YAXPAXI@Z:PROC		; __global_delete
EXTRN	??_ECGdiObject@@UAEPAXI@Z:PROC			; CGdiObject::`vector deleting destructor'
EXTRN	??_ECBrush@@UAEPAXI@Z:PROC			; CBrush::`vector deleting destructor'
EXTRN	??_ECThatboyEncryptFileEncoderApp@@UAEPAXI@Z:PROC ; CThatboyEncryptFileEncoderApp::`vector deleting destructor'
?theApp@@3VCThatboyEncryptFileEncoderApp@@A DB 0ccH DUP (?) ; theApp
_BSS	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ DD 019930522H
	DD	04H
	DD	FLAT:__unwindtable$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
__unwindtable$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$0
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$2
	DD	01H
	DD	FLAT:__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$3
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$1
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1CGdiObject@@UAE@XZ DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$??1CGdiObject@@UAE@XZ
	DD	01H
	DD	FLAT:__tryblocktable$??1CGdiObject@@UAE@XZ
	DD	2 DUP(00H)
	DD	00H
	DD	05H
__unwindtable$??1CGdiObject@@UAE@XZ DD 0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	01H
	DD	FLAT:__unwindfunclet$??1CGdiObject@@UAE@XZ$2
__tryblocktable$??1CGdiObject@@UAE@XZ DD 00H
	DD	00H
	DD	02H
	DD	01H
	DD	FLAT:__catchsym$??1CGdiObject@@UAE@XZ$3
__catchsym$??1CGdiObject@@UAE@XZ$3 DD 00H
	DD	FLAT:??_R0PAVCException@@@8
	DD	0fffffde4H
	DD	FLAT:__catch$??1CGdiObject@@UAE@XZ$0
?theApp$initializer$@@3P6AXXZA DD FLAT:??__EtheApp@@YAXXZ ; theApp$initializer$
; Function compile flags: /Ogtp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
;	COMDAT ?GetMessageMap@CThatboyEncryptFileEncoderApp@@MBEPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
?GetMessageMap@CThatboyEncryptFileEncoderApp@@MBEPBUAFX_MSGMAP@@XZ PROC ; CThatboyEncryptFileEncoderApp::GetMessageMap, COMDAT
; _this$ = ecx

; 16   : BEGIN_MESSAGE_MAP(CThatboyEncryptFileEncoderApp, CWinApp)

	mov	eax, OFFSET ?messageMap@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4U3@B
	ret	0
?GetMessageMap@CThatboyEncryptFileEncoderApp@@MBEPBUAFX_MSGMAP@@XZ ENDP ; CThatboyEncryptFileEncoderApp::GetMessageMap
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
;	COMDAT ?GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
?GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ PROC ; CThatboyEncryptFileEncoderApp::GetThisMessageMap, COMDAT

; 17   : 	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
; 18   : END_MESSAGE_MAP()

	mov	eax, OFFSET ?messageMap@?1??GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ@4U3@B
	ret	0
?GetThisMessageMap@CThatboyEncryptFileEncoderApp@@KGPBUAFX_MSGMAP@@XZ ENDP ; CThatboyEncryptFileEncoderApp::GetThisMessageMap
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
;	COMDAT ??0CThatboyEncryptFileEncoderApp@@QAE@XZ
_TEXT	SEGMENT
??0CThatboyEncryptFileEncoderApp@@QAE@XZ PROC		; CThatboyEncryptFileEncoderApp::CThatboyEncryptFileEncoderApp, COMDAT
; _this$dead$ = ecx

; 24   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	push	0
	mov	ecx, OFFSET ?theApp@@3VCThatboyEncryptFileEncoderApp@@A ; theApp
	call	DWORD PTR __imp_??0CWinApp@@QAE@PBD@Z
	mov	DWORD PTR ?theApp@@3VCThatboyEncryptFileEncoderApp@@A, OFFSET ??_7CThatboyEncryptFileEncoderApp@@6B@

; 25   : 	// TODO: 鍦ㄦ澶勬坊鍔犳瀯閫犱唬鐮侊紝
; 26   : 	// 灏嗘墍鏈夐噸瑕佺殑鍒濆鍖栨斁缃湪 InitInstance 涓?
; 27   : }

	mov	eax, OFFSET ?theApp@@3VCThatboyEncryptFileEncoderApp@@A ; theApp
	mov	esp, ebp
	pop	ebp
	ret	0
??0CThatboyEncryptFileEncoderApp@@QAE@XZ ENDP		; CThatboyEncryptFileEncoderApp::CThatboyEncryptFileEncoderApp
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ??_GCThatboyEncryptFileEncoderApp@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8						; size = 4
??_GCThatboyEncryptFileEncoderApp@@UAEPAXI@Z PROC	; CThatboyEncryptFileEncoderApp::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	call	DWORD PTR __imp_??1CWinApp@@UAE@XZ
	mov	eax, DWORD PTR ___flags$[ebp]
	test	al, 1
	je	SHORT $LN12@scalar
	test	al, 4
	jne	SHORT $LN3@scalar

; 112  : 	{ ::operator delete(p); }

	push	esi
	call	DWORD PTR __imp_??3@YAXPAX@Z
	add	esp, 4
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
$LN3@scalar:
	push	204					; 000000ccH
	push	esi
	call	?__global_delete@@YAXPAXI@Z		; __global_delete
	add	esp, 8
$LN12@scalar:
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
??_GCThatboyEncryptFileEncoderApp@@UAEPAXI@Z ENDP	; CThatboyEncryptFileEncoderApp::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??1CThatboyEncryptFileEncoderApp@@UAE@XZ
_TEXT	SEGMENT
??1CThatboyEncryptFileEncoderApp@@UAE@XZ PROC		; CThatboyEncryptFileEncoderApp::~CThatboyEncryptFileEncoderApp, COMDAT
; _this$ = ecx
	jmp	DWORD PTR __imp_??1CWinApp@@UAE@XZ
??1CThatboyEncryptFileEncoderApp@@UAE@XZ ENDP		; CThatboyEncryptFileEncoderApp::~CThatboyEncryptFileEncoderApp
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
;	COMDAT ??__EtheApp@@YAXXZ
text$di	SEGMENT
??__EtheApp@@YAXXZ PROC					; `dynamic initializer for 'theApp'', COMDAT

; 24   : {

	push	0
	mov	ecx, OFFSET ?theApp@@3VCThatboyEncryptFileEncoderApp@@A ; theApp
	call	DWORD PTR __imp_??0CWinApp@@QAE@PBD@Z

; 32   : CThatboyEncryptFileEncoderApp theApp;

	push	OFFSET ??__FtheApp@@YAXXZ		; `dynamic atexit destructor for 'theApp''

; 24   : {

	mov	DWORD PTR ?theApp@@3VCThatboyEncryptFileEncoderApp@@A, OFFSET ??_7CThatboyEncryptFileEncoderApp@@6B@

; 32   : CThatboyEncryptFileEncoderApp theApp;

	call	_atexit
	pop	ecx
	ret	0
??__EtheApp@@YAXXZ ENDP					; `dynamic initializer for 'theApp''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__FtheApp@@YAXXZ
text$yd	SEGMENT
??__FtheApp@@YAXXZ PROC					; `dynamic atexit destructor for 'theApp'', COMDAT
	mov	ecx, OFFSET ?theApp@@3VCThatboyEncryptFileEncoderApp@@A ; theApp
	jmp	DWORD PTR __imp_??1CWinApp@@UAE@XZ
??__FtheApp@@YAXXZ ENDP					; `dynamic atexit destructor for 'theApp''
text$yd	ENDS
; Function compile flags: /Ogtp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoderDlg.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin2.inl
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoderDlg.cpp
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp
;	COMDAT ?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ
_TEXT	SEGMENT
_dlg$ = -392						; size = 376
$T1 = -16						; size = 4
__$EHRec$ = -12						; size = 12
?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ PROC ; CThatboyEncryptFileEncoderApp::InitInstance, COMDAT
; _this$ = ecx

; 38   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 380				; 0000017cH
	push	esi
	push	edi
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	edi, ecx

; 39   : 	CWinApp::InitInstance();

	call	DWORD PTR __imp_?InitInstance@CWinApp@@UAEHXZ
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl

; 116  : 	{ return ::operator new(nSize); }

	push	12					; 0000000cH
	call	DWORD PTR __imp_??2@YAPAXI@Z
	add	esp, 4
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp

; 44   : 	CShellManager *pShellManager = new CShellManager;

	mov	DWORD PTR $T1[ebp], eax
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	test	eax, eax
	je	SHORT $LN9@InitInstan
	mov	ecx, eax
	call	DWORD PTR __imp_??0CShellManager@@QAE@XZ
	mov	esi, eax
	jmp	SHORT $LN10@InitInstan
$LN9@InitInstan:
	xor	esi, esi
$LN10@InitInstan:
	mov	DWORD PTR __$EHRec$[ebp+8], -1

; 45   : 
; 46   : 	// 婵�娲烩�淲indows Native鈥濊瑙夌鐞嗗櫒锛屼互渚垮湪 MFC 鎺т欢涓惎鐢ㄤ富棰?
; 47   : 	CMFCVisualManager::SetDefaultManager(RUNTIME_CLASS(CMFCVisualManagerWindows));

	call	DWORD PTR __imp_?GetThisClass@CMFCVisualManagerWindows@@SGPAUCRuntimeClass@@XZ
	push	eax
	call	DWORD PTR __imp_?SetDefaultManager@CMFCVisualManager@@SGXPAUCRuntimeClass@@@Z

; 48   : 
; 49   : 	// 鏍囧噯鍒濆鍖?
; 50   : 	// 濡傛灉鏈娇鐢ㄨ繖浜涘姛鑳藉苟甯屾湜鍑忓皬
; 51   : 	// 鏈�缁堝彲鎵ц鏂囦欢鐨勫ぇ灏忥紝鍒欏簲绉婚櫎涓嬪垪
; 52   : 	// 涓嶉渶瑕佺殑鐗瑰畾鍒濆鍖栦緥绋?
; 53   : 	// 鏇存敼鐢ㄤ簬瀛樺偍璁剧疆鐨勬敞鍐岃〃椤?
; 54   : 	// TODO: 搴旈�傚綋淇敼璇ュ瓧绗︿覆锛?
; 55   : 	// 渚嬪淇敼涓哄叕鍙告垨缁勭粐鍚?
; 56   : 	SetRegistryKey(_T("搴旂敤绋嬪簭鍚戝鐢熸垚鐨勬湰鍦板簲鐢ㄧ▼搴?));

	push	OFFSET ??_C@_0BP@MGHGNFFK@?S?$KG?S?C?$LD?L?P?r?O?r?$LF?$LM?I?z?$LD?I?$LF?D?$LB?$LO?$LF?X?S?$KG?S?C?$LD?L?P?r@
	mov	ecx, edi
	call	DWORD PTR __imp_?SetRegistryKey@CWinApp@@IAEXPBD@Z
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoderDlg.cpp

; 21   : 	: CDialogEx(IDDTEF_THATBOYENCRYPTFILEENCODER_DIALOG, pParent)

	push	0
	push	102					; 00000066H
	lea	ecx, DWORD PTR _dlg$[ebp]
	call	DWORD PTR __imp_??0CDialogEx@@QAE@IPAVCWnd@@@Z
	mov	DWORD PTR __$EHRec$[ebp+8], 1

; 22   : {

	lea	ecx, DWORD PTR _dlg$[ebp+216]
	mov	DWORD PTR _dlg$[ebp], OFFSET ??_7CThatboyEncryptFileEncoderDlg@@6B@
	call	DWORD PTR __imp_??0CToolTipCtrl@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+8], 2
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl

; 19   : 	{ return afxCurrentWinApp; }

	call	DWORD PTR __imp_?AfxGetModuleState@@YGPAVAFX_MODULE_STATE@@XZ
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin2.inl

; 1054 : 	{ return ::LoadIconW(AfxFindResourceHandle(ATL_MAKEINTRESOURCE(nIDResource),

	push	128					; 00000080H
	push	14					; 0000000eH
	push	128					; 00000080H
	call	DWORD PTR __imp_?AfxFindResourceHandle@@YGPAUHINSTANCE__@@PBD0@Z
	push	eax
	call	DWORD PTR __imp__LoadIconW@8
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoderDlg.cpp

; 23   : 	m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);

	mov	DWORD PTR _dlg$[ebp+208], eax
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp

; 59   : 	m_pMainWnd = &dlg;

	lea	eax, DWORD PTR _dlg$[ebp]
	mov	DWORD PTR __$EHRec$[ebp+8], 3

; 60   : 	INT_PTR nResponse = dlg.DoModal();

	mov	ecx, eax
	mov	DWORD PTR [edi+32], eax
	call	DWORD PTR __imp_?DoModal@CDialog@@UAEHXZ

; 61   : 	if (nResponse == IDOK)
; 62   : 	{
; 63   : 		// TODO: 鍦ㄦ鏀剧疆澶勭悊浣曟椂鐢?
; 64   : 		//  鈥滅‘瀹氣�濇潵鍏抽棴瀵硅瘽妗嗙殑浠ｇ爜
; 65   : 	}
; 66   : 	else if (nResponse == IDCANCEL)
; 67   : 	{
; 68   : 		// TODO: 鍦ㄦ鏀剧疆澶勭悊浣曟椂鐢?
; 69   : 		//  鈥滃彇娑堚�濇潵鍏抽棴瀵硅瘽妗嗙殑浠ｇ爜
; 70   : 	}
; 71   : 	else if (nResponse == -1)
; 72   : 	{
; 73   : 		TRACE(traceAppMsg, 0, "璀﹀憡: 瀵硅瘽妗嗗垱寤哄け璐ワ紝搴旂敤绋嬪簭灏嗘剰澶栫粓姝€�俓n");
; 74   : 		TRACE(traceAppMsg, 0, "璀﹀憡: 濡傛灉鎮ㄥ湪瀵硅瘽妗嗕笂浣跨敤 MFC 鎺т欢锛屽垯鏃犳硶 #define _AFX_NO_MFC_CONTROLS_IN_DIALOGS銆俓n");
; 75   : 	}
; 76   : 
; 77   : 	// 鍒犻櫎涓婇潰鍒涘缓鐨?shell 绠＄悊鍣ㄣ�?
; 78   : 	if (pShellManager != nullptr)

	test	esi, esi
	je	SHORT $LN11@InitInstan

; 79   : 	{
; 80   : 		delete pShellManager;

	mov	eax, DWORD PTR [esi]
	mov	ecx, esi
	push	1
	call	DWORD PTR [eax+4]
$LN11@InitInstan:
	lea	ecx, DWORD PTR _dlg$[ebp+216]
	call	DWORD PTR __imp_??1CToolTipCtrl@@UAE@XZ
	lea	ecx, DWORD PTR _dlg$[ebp+192]
	call	DWORD PTR __imp_??1CDialogImpl@@MAE@XZ
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl

; 130  : 	{ }

	lea	ecx, DWORD PTR _dlg$[ebp+180]
	mov	DWORD PTR _dlg$[ebp+180], OFFSET ??_7CBrush@@6B@
	call	??1CGdiObject@@UAE@XZ			; CGdiObject::~CGdiObject
	lea	ecx, DWORD PTR _dlg$[ebp]
	call	DWORD PTR __imp_??1CDialog@@UAE@XZ
; File E:\Visual Studio Application\文件加密算法设计\ThatboyEncryptFileEncoder\ThatboyEncryptFileEncoder.cpp

; 89   : 	return FALSE;

	xor	eax, eax

; 90   : }

	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$0:
	mov	ecx, DWORD PTR $T1[ebp]
	jmp	??3CObject@@SGXPAX@Z			; CObject::operator delete
__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$2:
	lea	ecx, DWORD PTR _dlg$[ebp]
	jmp	??1CDialogEx@@UAE@XZ
__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$3:
	lea	ecx, DWORD PTR _dlg$[ebp+216]
	jmp	DWORD PTR __imp_??1CToolTipCtrl@@UAE@XZ
__unwindfunclet$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ$1:
	lea	ecx, DWORD PTR _dlg$[ebp]
	jmp	??1CThatboyEncryptFileEncoderDlg@@UAE@XZ
__ehhandler$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-392]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?InitInstance@CThatboyEncryptFileEncoderApp@@UAEHXZ ENDP ; CThatboyEncryptFileEncoderApp::InitInstance
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
;	COMDAT ??1CThatboyEncryptFileEncoderDlg@@UAE@XZ
_TEXT	SEGMENT
??1CThatboyEncryptFileEncoderDlg@@UAE@XZ PROC		; CThatboyEncryptFileEncoderDlg::~CThatboyEncryptFileEncoderDlg, COMDAT
; _this$ = ecx

; 130  : 	{ }

	push	esi
	mov	esi, ecx
	lea	ecx, DWORD PTR [esi+216]
	call	DWORD PTR __imp_??1CToolTipCtrl@@UAE@XZ
	lea	ecx, DWORD PTR [esi+192]
	call	DWORD PTR __imp_??1CDialogImpl@@MAE@XZ
	lea	ecx, DWORD PTR [esi+180]
	mov	DWORD PTR [ecx], OFFSET ??_7CBrush@@6B@
	call	??1CGdiObject@@UAE@XZ			; CGdiObject::~CGdiObject
	mov	ecx, esi
	pop	esi
	jmp	DWORD PTR __imp_??1CDialog@@UAE@XZ
??1CThatboyEncryptFileEncoderDlg@@UAE@XZ ENDP		; CThatboyEncryptFileEncoderDlg::~CThatboyEncryptFileEncoderDlg
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
;	COMDAT ??1CDialogEx@@UAE@XZ
_TEXT	SEGMENT
??1CDialogEx@@UAE@XZ PROC				; CDialogEx::~CDialogEx, COMDAT
; _this$ = ecx

; 130  : 	{ }

	push	esi
	mov	esi, ecx
	lea	ecx, DWORD PTR [esi+192]
	call	DWORD PTR __imp_??1CDialogImpl@@MAE@XZ
	lea	ecx, DWORD PTR [esi+180]
	mov	DWORD PTR [ecx], OFFSET ??_7CBrush@@6B@
	call	??1CGdiObject@@UAE@XZ			; CGdiObject::~CGdiObject
	mov	ecx, esi
	pop	esi
	jmp	DWORD PTR __imp_??1CDialog@@UAE@XZ
??1CDialogEx@@UAE@XZ ENDP				; CDialogEx::~CDialogEx
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?GetApplicationRecoveryPingInterval@CWinApp@@UAEKXZ
_TEXT	SEGMENT
?GetApplicationRecoveryPingInterval@CWinApp@@UAEKXZ PROC ; CWinApp::GetApplicationRecoveryPingInterval, COMDAT
; _this$ = ecx

; 5370 : 	virtual DWORD GetApplicationRecoveryPingInterval() { return RECOVERY_DEFAULT_PING_INTERVAL; }  // Ping interval for RegisterApplicationRecoveryCallback

	mov	eax, 5000				; 00001388H
	ret	0
?GetApplicationRecoveryPingInterval@CWinApp@@UAEKXZ ENDP ; CWinApp::GetApplicationRecoveryPingInterval
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?GetApplicationRecoveryParameter@CWinApp@@UAEPAXXZ
_TEXT	SEGMENT
?GetApplicationRecoveryParameter@CWinApp@@UAEPAXXZ PROC	; CWinApp::GetApplicationRecoveryParameter, COMDAT
; _this$ = ecx

; 5369 : 	virtual LPVOID GetApplicationRecoveryParameter() { return NULL; }  // Parameter to be passed along to RegisterApplicationRecoveryCallback

	xor	eax, eax
	ret	0
?GetApplicationRecoveryParameter@CWinApp@@UAEPAXXZ ENDP	; CWinApp::GetApplicationRecoveryParameter
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?GetApplicationRestartFlags@CWinApp@@UAEKXZ
_TEXT	SEGMENT
?GetApplicationRestartFlags@CWinApp@@UAEKXZ PROC	; CWinApp::GetApplicationRestartFlags, COMDAT
; _this$ = ecx

; 5368 : 	virtual DWORD GetApplicationRestartFlags() { return 0; }  // Flags for RegisterApplicationRestart: default is none of RESTART_NO_CRASH/RESTART_NO_HANG/RESTART_NO_PATCH/RESTART_NO_REBOOT

	xor	eax, eax
	ret	0
?GetApplicationRestartFlags@CWinApp@@UAEKXZ ENDP	; CWinApp::GetApplicationRestartFlags
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?RestoreAutosavedFilesAtRestart@CWinApp@@UBEHXZ
_TEXT	SEGMENT
?RestoreAutosavedFilesAtRestart@CWinApp@@UBEHXZ PROC	; CWinApp::RestoreAutosavedFilesAtRestart, COMDAT
; _this$ = ecx

; 5366 : 	virtual BOOL RestoreAutosavedFilesAtRestart() const { return m_dwRestartManagerSupportFlags & AFX_RESTART_MANAGER_RESTORE_AUTOSAVED_FILES; }

	mov	eax, DWORD PTR [ecx+172]
	and	eax, 32					; 00000020H
	ret	0
?RestoreAutosavedFilesAtRestart@CWinApp@@UBEHXZ ENDP	; CWinApp::RestoreAutosavedFilesAtRestart
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?ReopenPreviousFilesAtRestart@CWinApp@@UBEHXZ
_TEXT	SEGMENT
?ReopenPreviousFilesAtRestart@CWinApp@@UBEHXZ PROC	; CWinApp::ReopenPreviousFilesAtRestart, COMDAT
; _this$ = ecx

; 5365 : 	virtual BOOL ReopenPreviousFilesAtRestart() const { return m_dwRestartManagerSupportFlags & AFX_RESTART_MANAGER_REOPEN_PREVIOUS_FILES; }

	mov	eax, DWORD PTR [ecx+172]
	and	eax, 16					; 00000010H
	ret	0
?ReopenPreviousFilesAtRestart@CWinApp@@UBEHXZ ENDP	; CWinApp::ReopenPreviousFilesAtRestart
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?SupportsAutosaveAtInterval@CWinApp@@UBEHXZ
_TEXT	SEGMENT
?SupportsAutosaveAtInterval@CWinApp@@UBEHXZ PROC	; CWinApp::SupportsAutosaveAtInterval, COMDAT
; _this$ = ecx

; 5364 : 	virtual BOOL SupportsAutosaveAtInterval() const { return m_dwRestartManagerSupportFlags & AFX_RESTART_MANAGER_AUTOSAVE_AT_INTERVAL; }

	mov	eax, DWORD PTR [ecx+172]
	and	eax, 8
	ret	0
?SupportsAutosaveAtInterval@CWinApp@@UBEHXZ ENDP	; CWinApp::SupportsAutosaveAtInterval
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?SupportsAutosaveAtRestart@CWinApp@@UBEHXZ
_TEXT	SEGMENT
?SupportsAutosaveAtRestart@CWinApp@@UBEHXZ PROC		; CWinApp::SupportsAutosaveAtRestart, COMDAT
; _this$ = ecx

; 5363 : 	virtual BOOL SupportsAutosaveAtRestart() const { return m_dwRestartManagerSupportFlags & AFX_RESTART_MANAGER_AUTOSAVE_AT_RESTART; }

	mov	eax, DWORD PTR [ecx+172]
	and	eax, 4
	ret	0
?SupportsAutosaveAtRestart@CWinApp@@UBEHXZ ENDP		; CWinApp::SupportsAutosaveAtRestart
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?SupportsApplicationRecovery@CWinApp@@UBEHXZ
_TEXT	SEGMENT
?SupportsApplicationRecovery@CWinApp@@UBEHXZ PROC	; CWinApp::SupportsApplicationRecovery, COMDAT
; _this$ = ecx

; 5362 : 	virtual BOOL SupportsApplicationRecovery() const { return m_dwRestartManagerSupportFlags & AFX_RESTART_MANAGER_SUPPORT_RECOVERY; }

	mov	eax, DWORD PTR [ecx+172]
	and	eax, 2
	ret	0
?SupportsApplicationRecovery@CWinApp@@UBEHXZ ENDP	; CWinApp::SupportsApplicationRecovery
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin.h
;	COMDAT ?SupportsRestartManager@CWinApp@@UBEHXZ
_TEXT	SEGMENT
?SupportsRestartManager@CWinApp@@UBEHXZ PROC		; CWinApp::SupportsRestartManager, COMDAT
; _this$ = ecx

; 5361 : 	virtual BOOL SupportsRestartManager() const { return m_dwRestartManagerSupportFlags & AFX_RESTART_MANAGER_SUPPORT_RESTART; }

	mov	eax, DWORD PTR [ecx+172]
	and	eax, 1
	ret	0
?SupportsRestartManager@CWinApp@@UBEHXZ ENDP		; CWinApp::SupportsRestartManager
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ??_GCBrush@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8						; size = 4
??_GCBrush@@UAEPAXI@Z PROC				; CBrush::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl

; 130  : 	{ }

	push	esi
	mov	esi, ecx
	mov	DWORD PTR [esi], OFFSET ??_7CBrush@@6B@
	call	??1CGdiObject@@UAE@XZ			; CGdiObject::~CGdiObject
	mov	eax, DWORD PTR ___flags$[ebp]
	test	al, 1
	je	SHORT $LN12@scalar
	test	al, 4
	jne	SHORT $LN3@scalar
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl

; 112  : 	{ ::operator delete(p); }

	push	esi
	call	DWORD PTR __imp_??3@YAXPAX@Z
	add	esp, 4
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
$LN3@scalar:
	push	8
	push	esi
	call	?__global_delete@@YAXPAXI@Z		; __global_delete
	add	esp, 8
$LN12@scalar:
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
??_GCBrush@@UAEPAXI@Z ENDP				; CBrush::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ??_GCGdiObject@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8						; size = 4
??_GCGdiObject@@UAEPAXI@Z PROC				; CGdiObject::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	call	??1CGdiObject@@UAE@XZ			; CGdiObject::~CGdiObject
	mov	eax, DWORD PTR ___flags$[ebp]
	test	al, 1
	je	SHORT $LN9@scalar
	test	al, 4
	jne	SHORT $LN3@scalar

; 112  : 	{ ::operator delete(p); }

	push	esi
	call	DWORD PTR __imp_??3@YAXPAX@Z
	add	esp, 4
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
$LN3@scalar:
	push	8
	push	esi
	call	?__global_delete@@YAXPAXI@Z		; __global_delete
	add	esp, 8
$LN9@scalar:
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
??_GCGdiObject@@UAEPAXI@Z ENDP				; CGdiObject::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ?Serialize@CObject@@UAEXAAVCArchive@@@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?Serialize@CObject@@UAEXAAVCArchive@@@Z PROC		; CObject::Serialize, COMDAT
; _this$ = ecx

; 106  : 	{ /* CObject does not serialize anything by default */ }

	ret	4
?Serialize@CObject@@UAEXAAVCArchive@@@Z ENDP		; CObject::Serialize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ?AssertValid@CObject@@UBEXXZ
_TEXT	SEGMENT
?AssertValid@CObject@@UBEXXZ PROC			; CObject::AssertValid, COMDAT
; _this$ = ecx

; 120  : 	{ /* no asserts in release builds */ }

	ret	0
?AssertValid@CObject@@UBEXXZ ENDP			; CObject::AssertValid
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ?Dump@CObject@@UBEXAAVCDumpContext@@@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?Dump@CObject@@UBEXAAVCDumpContext@@@Z PROC		; CObject::Dump, COMDAT
; _this$ = ecx

; 122  : 	{ /* no dumping in release builds */ }

	ret	4
?Dump@CObject@@UBEXAAVCDumpContext@@@Z ENDP		; CObject::Dump
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ??1CObject@@UAE@XZ
_TEXT	SEGMENT
??1CObject@@UAE@XZ PROC					; CObject::~CObject, COMDAT
; _this$ = ecx

; 104  : 	{ }

	ret	0
??1CObject@@UAE@XZ ENDP					; CObject::~CObject
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
;	COMDAT ??1CGdiObject@@UAE@XZ
_TEXT	SEGMENT
_pException$4 = -540					; size = 4
_strMsg$5 = -536					; size = 4
_szErrorMessage$6 = -532				; size = 512
__$ArrayPad$ = -20					; size = 4
__$EHRec$ = -16						; size = 16
??1CGdiObject@@UAE@XZ PROC				; CGdiObject::~CGdiObject, COMDAT
; _this$ = ecx

; 74   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1CGdiObject@@UAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 528				; 00000210H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	ebx
	push	esi
	push	edi
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR __$EHRec$[ebp], esp
	mov	DWORD PTR [ecx], OFFSET ??_7CGdiObject@@6B@

; 75   : 	AFX_BEGIN_DESTRUCTOR

	mov	DWORD PTR __$EHRec$[ebp+12], 0

; 76   : 	DeleteObject();

	call	DWORD PTR __imp_?DeleteObject@CGdiObject@@QAEHXZ
$LN18@CGdiObject:

; 78   : }

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
__catch$??1CGdiObject@@UAE@XZ$0:

; 77   : 	AFX_END_DESTRUCTOR

	lea	ecx, DWORD PTR _strMsg$5[ebp]
	call	DWORD PTR __imp_??0?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAE@XZ
	mov	BYTE PTR __$EHRec$[ebp+12], 2
	lea	ecx, DWORD PTR _szErrorMessage$6[ebp]
	mov	esi, DWORD PTR _pException$4[ebp]
	push	0
	push	512					; 00000200H
	push	ecx
	mov	eax, DWORD PTR [esi]
	mov	ecx, esi
	call	DWORD PTR [eax+20]
	test	eax, eax
	je	SHORT $LN9@CGdiObject
	lea	eax, DWORD PTR _szErrorMessage$6[ebp]
	push	eax
	push	77					; 0000004dH
	push	OFFSET ??_C@_0HD@FGOICIBN@C?3?2Program?5Files?5?$CIx86?$CJ?2Microsof@
	push	OFFSET ??_C@_0BP@OIEOKIDM@Exception?5thrown?5in?5destructor@
	lea	eax, DWORD PTR _strMsg$5[ebp]
	push	OFFSET ??_C@_0BB@HBOOMJBF@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ?6?$CFTs@
	push	eax
	call	DWORD PTR __imp_?Format@?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAAXPBDZZ
	add	esp, 24					; 00000018H
	jmp	SHORT $LN10@CGdiObject
$LN9@CGdiObject:
	push	77					; 0000004dH
	push	OFFSET ??_C@_0HD@FGOICIBN@C?3?2Program?5Files?5?$CIx86?$CJ?2Microsof@
	push	OFFSET ??_C@_0BP@OIEOKIDM@Exception?5thrown?5in?5destructor@
	lea	eax, DWORD PTR _strMsg$5[ebp]
	push	OFFSET ??_C@_0N@OMEMOKLE@?$CFTs?5?$CI?$CFTs?3?$CFd?$CJ@
	push	eax
	call	DWORD PTR __imp_?Format@?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAAXPBDZZ
	add	esp, 20					; 00000014H
$LN10@CGdiObject:
	push	0
	push	0
	push	DWORD PTR _strMsg$5[ebp]
	call	DWORD PTR __imp_?AfxMessageBox@@YGHPBDII@Z
	lea	ecx, DWORD PTR _strMsg$5[ebp]
	call	DWORD PTR __imp_??1?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAE@XZ
	mov	eax, DWORD PTR [esi]
	mov	ecx, esi
	push	1
	call	DWORD PTR [eax+4]
	mov	eax, $LN18@CGdiObject
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??1CGdiObject@@UAE@XZ$2:
	lea	ecx, DWORD PTR _strMsg$5[ebp]
	jmp	DWORD PTR __imp_??1?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@QAE@XZ
__ehhandler$??1CGdiObject@@UAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-544]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-8]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1CGdiObject@@UAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1CGdiObject@@UAE@XZ ENDP				; CGdiObject::~CGdiObject
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afxwin1.inl
;	COMDAT ??1CBrush@@UAE@XZ
_TEXT	SEGMENT
??1CBrush@@UAE@XZ PROC					; CBrush::~CBrush, COMDAT
; _this$ = ecx

; 130  : 	{ }

	mov	DWORD PTR [ecx], OFFSET ??_7CBrush@@6B@
	jmp	??1CGdiObject@@UAE@XZ			; CGdiObject::~CGdiObject
??1CBrush@@UAE@XZ ENDP					; CBrush::~CBrush
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ??2CObject@@SGPAXI@Z
_TEXT	SEGMENT
??2CObject@@SGPAXI@Z PROC				; CObject::operator new, COMDAT
; _nSize$dead$ = ecx

; 116  : 	{ return ::operator new(nSize); }

	push	12					; 0000000cH
	call	DWORD PTR __imp_??2@YAPAXI@Z
	add	esp, 4
	ret	0
??2CObject@@SGPAXI@Z ENDP				; CObject::operator new
_TEXT	ENDS
; Function compile flags: /Ogtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\atlmfc\include\afx.inl
;	COMDAT ??3CObject@@SGXPAX@Z
_TEXT	SEGMENT
??3CObject@@SGXPAX@Z PROC				; CObject::operator delete, COMDAT
; _p$ = ecx

; 112  : 	{ ::operator delete(p); }

	push	ecx
	call	DWORD PTR __imp_??3@YAXPAX@Z
	pop	ecx
	ret	0
??3CObject@@SGXPAX@Z ENDP				; CObject::operator delete
_TEXT	ENDS
END
